// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Set pruebas', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Prueba Registro usuario nuevo', async function() {
    await driver.get("https://buggy.justtestit.org/")
    await driver.manage().window().setRect({ width: 974, height: 1032 })
    await driver.findElement(By.linkText("Register")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("Pepe156421")
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("Pedro")
    await driver.findElement(By.css("form:nth-child(2)")).click()
    await driver.findElement(By.id("lastName")).click()
    await driver.findElement(By.id("lastName")).sendKeys("Rodriguez")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Pepe2023*")
    await driver.findElement(By.id("confirmPassword")).click()
    await driver.findElement(By.id("confirmPassword")).sendKeys("Pepe2023*")
    await driver.findElement(By.css(".btn-default")).click()
    assert(await driver.findElement(By.css(".result")).getText() == "Registration is successful")
  })
  it('Validacion pagina de inicio', async function() {
    await driver.get("https://buggy.justtestit.org/")
    assert(await driver.getTitle() == "Buggy Cars Rating")
    await driver.manage().window().setRect({ width: 974, height: 1032 })
    {
      const elements = await driver.findElements(By.css(".center-block > .img-fluid"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".col-md-4:nth-child(1) .card-header")).getText() == "Popular Make")
    assert(await driver.findElement(By.css(".col-md-4:nth-child(2) .card-header")).getText() == "Popular Model")
    assert(await driver.findElement(By.css(".col-md-4:nth-child(3) .card-header")).getText() == "Overall Rating")
    {
      const elements = await driver.findElements(By.css("a:nth-child(1) > img"))
      assert(elements.length)
    }
  })
})
